"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import flow_pb2 as _flow_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class FlowClusterStub:
    """─── FlowCluster Service ──────────────────────────────────────"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> FlowClusterAsyncStub: ...
    StreamTasks: _grpc.StreamStreamMultiCallable[_flow_pb2.WorkerMessage, _flow_pb2.MasterMessage]
    """Bidirectional streaming between Worker and Master"""

@_typing.type_check_only
class FlowClusterAsyncStub(FlowClusterStub):
    """─── FlowCluster Service ──────────────────────────────────────"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamTasks: _aio.StreamStreamMultiCallable[_flow_pb2.WorkerMessage, _flow_pb2.MasterMessage]  # type: ignore[assignment]
    """Bidirectional streaming between Worker and Master"""

class FlowClusterServicer(metaclass=_abc_1.ABCMeta):
    """─── FlowCluster Service ──────────────────────────────────────"""

    @_abc_1.abstractmethod
    def StreamTasks(
        self,
        request_iterator: _MaybeAsyncIterator[_flow_pb2.WorkerMessage],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_flow_pb2.MasterMessage], _abc.AsyncIterator[_flow_pb2.MasterMessage]]:
        """Bidirectional streaming between Worker and Master"""

def add_FlowClusterServicer_to_server(servicer: FlowClusterServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
