"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class WorkerMessage(_message.Message):
    """─── Worker → Master Messages ─────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    REGISTER_FIELD_NUMBER: _builtins.int
    HEARTBEAT_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    COMPLETED_FIELD_NUMBER: _builtins.int
    FAILED_FIELD_NUMBER: _builtins.int
    PROJECT_MAPPING_FIELD_NUMBER: _builtins.int
    ACCOUNT_UPDATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def register(self) -> Global___RegisterRequest: ...
    @_builtins.property
    def heartbeat(self) -> Global___HeartbeatRequest: ...
    @_builtins.property
    def progress(self) -> Global___ProgressReport: ...
    @_builtins.property
    def completed(self) -> Global___CompletedReport: ...
    @_builtins.property
    def failed(self) -> Global___FailedReport: ...
    @_builtins.property
    def project_mapping(self) -> Global___ProjectMapping: ...
    @_builtins.property
    def account_update(self) -> Global___AccountUpdate: ...
    def __init__(
        self,
        *,
        register: Global___RegisterRequest | None = ...,
        heartbeat: Global___HeartbeatRequest | None = ...,
        progress: Global___ProgressReport | None = ...,
        completed: Global___CompletedReport | None = ...,
        failed: Global___FailedReport | None = ...,
        project_mapping: Global___ProjectMapping | None = ...,
        account_update: Global___AccountUpdate | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["account_update", b"account_update", "completed", b"completed", "failed", b"failed", "heartbeat", b"heartbeat", "payload", b"payload", "progress", b"progress", "project_mapping", b"project_mapping", "register", b"register"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_update", b"account_update", "completed", b"completed", "failed", b"failed", "heartbeat", b"heartbeat", "payload", b"payload", "progress", b"progress", "project_mapping", b"project_mapping", "register", b"register"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["register", "heartbeat", "progress", "completed", "failed", "project_mapping", "account_update"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___WorkerMessage: _TypeAlias = WorkerMessage  # noqa: Y015

@_typing.final
class RegisterRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ProjectMappingsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    WORKER_ID_FIELD_NUMBER: _builtins.int
    ACCOUNT_FIELD_NUMBER: _builtins.int
    PROJECT_MAPPINGS_FIELD_NUMBER: _builtins.int
    CACHED_ASSETS_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    account: _builtins.str
    @_builtins.property
    def project_mappings(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """alias -> local_uuid"""

    @_builtins.property
    def cached_assets(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Already cached asset names"""

    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        account: _builtins.str = ...,
        project_mappings: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        cached_assets: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account", b"account", "cached_assets", b"cached_assets", "project_mappings", b"project_mappings", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterRequest: _TypeAlias = RegisterRequest  # noqa: Y015

@_typing.final
class HeartbeatRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HeartbeatRequest: _TypeAlias = HeartbeatRequest  # noqa: Y015

@_typing.final
class ProgressReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    PROGRESS_PERCENT_FIELD_NUMBER: _builtins.int
    PROGRESS_TEXT_FIELD_NUMBER: _builtins.int
    ELAPSED_SECONDS_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    phase: _builtins.str
    message: _builtins.str
    progress_percent: _builtins.int
    progress_text: _builtins.str
    elapsed_seconds: _builtins.float
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        phase: _builtins.str = ...,
        message: _builtins.str = ...,
        progress_percent: _builtins.int = ...,
        progress_text: _builtins.str = ...,
        elapsed_seconds: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["elapsed_seconds", b"elapsed_seconds", "job_id", b"job_id", "message", b"message", "phase", b"phase", "progress_percent", b"progress_percent", "progress_text", b"progress_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProgressReport: _TypeAlias = ProgressReport  # noqa: Y015

@_typing.final
class CompletedReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    WORKER_ID_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    PRODUCED_ASSETS_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    worker_id: _builtins.str
    @_builtins.property
    def result(self) -> _struct_pb2.Struct:
        """Task result payload"""

    @_builtins.property
    def produced_assets(self) -> _containers.RepeatedCompositeFieldContainer[Global___AssetInfo]:
        """Assets produced by worker"""

    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        worker_id: _builtins.str = ...,
        result: _struct_pb2.Struct | None = ...,
        produced_assets: _abc.Iterable[Global___AssetInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id", "produced_assets", b"produced_assets", "result", b"result", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CompletedReport: _TypeAlias = CompletedReport  # noqa: Y015

@_typing.final
class AssetInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    LOCAL_PATH_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    kind: _builtins.str
    """"image" | "character" | "video" """
    local_path: _builtins.str
    """Worker local temp path"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        kind: _builtins.str = ...,
        local_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kind", b"kind", "local_path", b"local_path", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssetInfo: _TypeAlias = AssetInfo  # noqa: Y015

@_typing.final
class FailedReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    WORKER_ID_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    worker_id: _builtins.str
    error: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        worker_id: _builtins.str = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "job_id", b"job_id", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FailedReport: _TypeAlias = FailedReport  # noqa: Y015

@_typing.final
class ProjectMapping(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    PROJECT_ALIAS_FIELD_NUMBER: _builtins.int
    LOCAL_UUID_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    project_alias: _builtins.str
    local_uuid: _builtins.str
    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        project_alias: _builtins.str = ...,
        local_uuid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["local_uuid", b"local_uuid", "project_alias", b"project_alias", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProjectMapping: _TypeAlias = ProjectMapping  # noqa: Y015

@_typing.final
class AccountUpdate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    BALANCE_FIELD_NUMBER: _builtins.int
    DAILY_FREE_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    email: _builtins.str
    balance: _builtins.int
    daily_free: _builtins.int
    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        email: _builtins.str = ...,
        balance: _builtins.int | None = ...,
        daily_free: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_balance", b"_balance", "_daily_free", b"_daily_free", "balance", b"balance", "daily_free", b"daily_free"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_balance", b"_balance", "_daily_free", b"_daily_free", "balance", b"balance", "daily_free", b"daily_free", "email", b"email", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__balance: _TypeAlias = _typing.Literal["balance"]  # noqa: Y015
    _WhichOneofArgType__balance: _TypeAlias = _typing.Literal["_balance", b"_balance"]  # noqa: Y015
    _WhichOneofReturnType__daily_free: _TypeAlias = _typing.Literal["daily_free"]  # noqa: Y015
    _WhichOneofArgType__daily_free: _TypeAlias = _typing.Literal["_daily_free", b"_daily_free"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__balance) -> _WhichOneofReturnType__balance | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__daily_free) -> _WhichOneofReturnType__daily_free | None: ...

Global___AccountUpdate: _TypeAlias = AccountUpdate  # noqa: Y015

@_typing.final
class MasterMessage(_message.Message):
    """─── Master → Worker Messages ─────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    ACK_FIELD_NUMBER: _builtins.int
    EXECUTE_FIELD_NUMBER: _builtins.int
    CANCEL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ack(self) -> Global___RegisterAck: ...
    @_builtins.property
    def execute(self) -> Global___ExecuteTask: ...
    @_builtins.property
    def cancel(self) -> Global___CancelTask: ...
    def __init__(
        self,
        *,
        ack: Global___RegisterAck | None = ...,
        execute: Global___ExecuteTask | None = ...,
        cancel: Global___CancelTask | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ack", b"ack", "cancel", b"cancel", "execute", b"execute", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ack", b"ack", "cancel", b"cancel", "execute", b"execute", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["ack", "execute", "cancel"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___MasterMessage: _TypeAlias = MasterMessage  # noqa: Y015

@_typing.final
class RegisterAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    success: _builtins.bool
    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterAck: _TypeAlias = RegisterAck  # noqa: Y015

@_typing.final
class ExecuteTask(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    TASK_TYPE_FIELD_NUMBER: _builtins.int
    PROJECT_ALIAS_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    REQUIRED_ASSETS_FIELD_NUMBER: _builtins.int
    PARENT_JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    task_type: _builtins.str
    project_alias: _builtins.str
    parent_job_id: _builtins.str
    """Non-empty for broadcast child tasks"""
    @_builtins.property
    def params(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def required_assets(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Assets needed before execution"""

    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        task_type: _builtins.str = ...,
        project_alias: _builtins.str = ...,
        params: _struct_pb2.Struct | None = ...,
        required_assets: _abc.Iterable[_builtins.str] | None = ...,
        parent_job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id", "params", b"params", "parent_job_id", b"parent_job_id", "project_alias", b"project_alias", "required_assets", b"required_assets", "task_type", b"task_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecuteTask: _TypeAlias = ExecuteTask  # noqa: Y015

@_typing.final
class CancelTask(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelTask: _TypeAlias = CancelTask  # noqa: Y015
